### PR TITLE
App framework refactoring and some cleanup etc.

### PR DESCRIPTION
**Pull request by firetech**
- Refactor the app framework a bit. Needs more work, but is in a working state (for digital watches, not for analog). Lays the groundwork for separate apps, but is (in these commits) only used for running internal apps "stand-alone" (not as idle pages). See commit ce12ddc7 for more info.
- Remove support for garthy's (outdated) in-firmware music app, as discussed.
- Add container actions, allowing for nestable actions. Using this, give notification actions their own sub-list and increase notification history to 15.
- Make it possible to toggle apps between stand-alone and idle pages by long-pressing the exit app/next page button.
- Add a setting (for the digital watch) that draws clock-less widget pages in the application buffer instead of the idle buffer. This has the benefit of always making the clock visible when the watch loses connection, but will disable the built-in button actions (settings, status, etc.) on the affected pages.
- Some more cleanup here and there.

### CODE REVIEW

**Comment by firetech** [comment]
I had to distract myself today morning, so I did this. Waiting for a job interview until 1 pm isn't healthy on my nerves. ;)

**Comment by benjymous** [comment]
Looks good - makes a nice stopgap till I get a proper configuration options into the framework.

Good luck with the interview!

**Comment by firetech** [comment]
Thanks, I've had the interview already, and I'm back coding. ;)

Right now, I'm trying to implement nestable actions (ie. a tree of actions), mostly thinking about how to do the rendering. That way, notifications won't clutter the actions list as much. :)

**Comment by benjymous** [comment]
Sounds good - that's actually something I'd thought about myself - You could quite easily build a "choose your own adventure" type game just powered by Actions!

Fyi, I've created a wiki page with some random thoughts on dev plans:

https://github.com/benjymous/MWM-for-Android/wiki/Braindump

**Comment by firetech** [comment]
Nice ideas, I'll keep that page in mind in the future, marking any stuff I'm working on. :)

**Comment by firetech** [comment]
Pull request updated with nestable actions. :)

**Comment by firetech** [comment]
I'm thinking about using the new app framweork to implement the last point in the Braindump list, making the Actions app more central in the interface. Maybe replace the replay button with an "Actions" button.

My idea is mostly to make the Actions app _the_ way to launch other apps (in effect removing the checkboxes for enabling/disabling the actions app and the music app). Perhaps make long press on the app exit button toggle the app as an idle page. I'm not really fond of app idle pages myself, and if it was just up to me, they could go, but I guess some people like them.

What are your thoughts on the subject?

**Comment by benjymous** [comment]
The main issue is keeping compatibility / consistency for the Analog watch - remember it only has three buttons rather than six, so you basically get the middle button to switch pages, and the top and bottom buttons are available for extra functions on the app pages. 

So in my opinion the idle app pages need to stay, but I don't see any reason why you can't have apps that stay open as pages vs apps that open on demand and go away when you close them.

**Comment by firetech** [comment]
Yeah, that is somewhat of a problem.

Do the top and bottom buttons have any function on the widget pages?

**Comment by benjymous** [comment]
Yeah, they bring up the settings menu and phone status, so it doesn't really make sense to override them. Code can also detect when the middle button is pulled out, and provide different functionality, but again that's already used in the idle mode for additional settings. You could potentially have Actions on a long press of the middle button, but I try and avoid using long presses for frequently used things as it's a bit hit and miss whether you hold it long enough to properly trigger it, which doesn't make for a good user experience. :-\

**Comment by firetech** [comment]
I thought about it, and figured that "go to top" is more usable than "up one level". Therefore, commit cd45519 ;)

**Comment by firetech** [comment]
Two new commits. The first one implements part of my idea above (ie. toggling apps between stand-alone and idle pages). The second one is a setting (defaults to enabled) for the digital watch that, in effect, always makes the clock reachable when the watch loses connection to the phone.

**Comment by benjymous** [comment]
Looks good - hopefully I'll actually get time to test this all, and get everything fixed up to work on the Analog watch!

**Comment by benjymous** [comment]
Actually merged! :)

**Comment by firetech** [comment]
In the meantime I'll add even more features, making it impossible for you to keep up. :P

(Just kidding.)

**Comment by benjymous** [comment]
I'll also get going on the framework to let external apps work nicely with the app pages, and to publish actions.

If you're looking for any other small tasks to do, I was planning on wrapping all the "demo" actions behind a settings option, so that "normal" users can enable them to see what's possible, but hide them away most of the time

**Comment by firetech** [comment]
I just took a look at the Braindump. Does my idle page/stand-alone toggle satisfy point 4 (Add option to close Idle apps)? Or did you mean remove apps from the (running) system? Should that even be possible (for internal apps)?

**Comment by firetech** [comment]
Also, I'm thinking about ways to reduce the complexity of the MWM app by separating it into smaller apps. Not going the MetaWatchCore route and rewriting everything, but splitting out the most separate parts (like weather, Gmail and K9, for example) into their own .apk's. What do you think about that?

**Comment by benjymous** [comment]
My idea was that apps would be launchable into the "idle page" state, 
so you could have multiple apps open and easily switchable between (e.g. 
having a Media player, a full screen calendar, and a stocks app) - you'd 
be able to launch apps from the Actions screen, and have them added to 
the idle pages, but also be able to close an idle page app.

I'd probably have the top-right have the switch page on short press, 
and close on long press for closable apps, and perhaps have an option to 
make app loading work in a "temporary popup" manner, the way your 
changes launch the media player.

**Comment by benjymous** [comment]
Yeah - my main worry would be the memory footprint - some chunks would 
need services running, which would dig into the available memory on the 
phone (although this may also provide a benefit if parts of the app 
don't need to be open all the time)

I'm planning on making a simple stocks app which will include widgets, 
an external app, and external actions, so that will be a good testcase 
for how much memory such an external service will use - if it seems good 
then we can move other parts to the same structure.

**Comment by firetech** [comment]
Sounds like good plans. _:)_
On May 28, 2012 9:28 PM, "benjymous" <
reply@reply.github.com>
wrote:

**Pull request merged**
