### PR TITLE
Improved location updates

### PR DESCRIPTION
**Pull request by DiogoNeves**
Instead of requesting updates every half-hour, any component that requires an up-to-date location can simply get the last best known location.
If this location isn't good enough it'll request a single update from the system and use as little power as possible.

This should fix issue #65

### CODE REVIEW

**Comment by DiogoNeves** [comment]
Should I change it? :)

**Comment by benjymous** [comment]
Sorry, been busy all weekend, so haven't had a chance to merge the changes over yet - I'll create a branch for v1.23 so I can keep the 1.22 code live (as I'm planning another bugfix release on that side)

Also need to assess the changes that will be necessary for compatibility with the Strata's 4.0 firmware, which could take a while!

**Comment by DiogoNeves** [comment]
Hey :) no problem.
Do you need any help with it?
I'm getting one of the new Stratas, we can test together at some point...

**Comment by benjymous** [comment]
Finally got around to merging this in - will give it a go for a few days and make sure it's all working as expected

**Pull request merged**
