### PR TITLE
Avoid instantly disappearing notifications (and a minor cleanup)

### PR DESCRIPTION
**Pull request by firetech**
I'm not 100% sure if this patch is a good idea, but it seems to solve a problem I'm having.

Since flashing firmware 0.10.X on my watch, I started having issues with notifications disappearing more or less immediately after they were sent (while the watch was still vibrating). Some investigations showed that this was because MWM sometimes started the timeout countdown well before the notification actually was shown (probably because of sniff mode ), causing MWM to call Protocol.exitNotification() too early.

This patch waits for a mode change message from the watch before starting the timeout. Since I don't have an analog watch, I don't know if it sends a mode change message when it receives notifications, so this patch seriously needs analog testing. As I said, I'm not entirely sure that this patch is a good idea, but the limited testing I have done has been successful. Based on log output, the timeout seems to start quite instantly after the notification is shown. The question is if the notification system can lock up somehow, especially on the analog watch. I have tested quick series of notifications without issues.

I also cleaned up calls to Protocol.updateLcdDisplay(), replacing explicitly given parameters (like 0 or 2) with the already existing named constants MetaWatchService.WatchBuffers.*, mostly because I was thinking about a different way to fix the problem.

### CODE REVIEW

**Comment by benjymous** [comment]
Nice work - yes, this has been an annoyance for me ever since I had the watch - I'll give it a good test on both watches :)

**Comment by firetech** [comment]
I hope it works for you too, then. :)

**Comment by firetech** [comment]
Hmm... Today I woke up with a notification queue length of 34. Something went bad during the night

However,  I _think_ that I added the timeout in the modeChanged.wait() call _after_ compiling the code for my phone. Have you had any issues?

EDIT: I'm quite sure the code on my phone did not have the timeout in modeChanged.wait(). The file motification time of Notification.java on my laptop was 40 minutes after the modification time of the apk on my phone. ;)

**Comment by benjymous** [comment]
I haven't noticed it get stuck in normal usage, but I did a quick test after I received your message (hammered every notify option on the tests screen) and found it did get stuck after a while (though it did unstick itself on its own after a while)

One possible culprit is something I've been trying to track down for a while - it seems something sometimes pushes the watch back into Idle mode, but MWM still thinks its in notification mode, so its sat their, waiting, in a confused state.  This is most noticeable when it happens with a sticky notification, since to the user it just looks like the watch has returned to the idle screen and has locked up, since MWM won't respond to the idle presses as it thinks its still in notification mode, and the watch can't dismiss the notification as the watch thinks it's in idle mode.

Perhaps some extra checks on mode change could detect if the watch has left notification mode when NotificationSender is still active, and put it back into notification mode.

**Comment by firetech** [comment]
That is a good idea to try out. I haven't checked the payload of the mode change message, but it _may_ contain the new mode. There were quite a few bytes in the message, after all. ;)

**Comment by benjymous** [comment]
If not, it'd certainly be useful to add :)

(Do you know if there's any way for MWM to find out what fw version the watch is running? - If not, adding a version string to the Get Device Type message would certainly be useful)

**Comment by benjymous** [comment]
I've just committed a load of changes that should help debug what's going on with the notification queue.

Each notification object now has a description, and I've added an option to display what's in the queue (and what the notificationsender thinks it's doing) on the status screen.

**Comment by firetech** [comment]
The mode change notifcation doesn't seem to contain any info about to/from mode (the data is the same when switching to notification mode and when switching back to idle).

I can agree that a firmware version message would be useful. If you're hinting that I should add one to my firmware builds, I'm not really willing to change the protocol code, in order to not break any compatibility...

I'll try your changes and check the log for problems.

**Comment by firetech** [comment]
Ah. I've found another reason for a deadlock, which I guess is what happened to me during the night (I tried removing the wait() timeout and hammered some notifications): a watch crash and restart when showing the notification. This happens to me in rare situations with firmware 0.10.X, less rare when the phone hammers the watch with data. I'll make a simple patch for that. Pull request incoming. ;)

**Comment by firetech** [comment]
It just occurred to me that the reason behind [the problem you described](https://github.com/benjymous/MWM-for-Android/pull/21#issuecomment-5666695) with the watch returning to idle without MWM knowing about it, probably is that the watch has an internal timeout for all modes except idle, which defaults to 30 seconds (stored in Nval).

This means that if one wants to have notifications showing longer than 30 seconds, MWM will have to either reset the timeout every now and then (for example by resending the screen), or increase the timeout using an Nval Operation.

**Comment by benjymous** [comment]
Hmm - maybe, I'll have a dig.

FYI I've just pushed my latest chunk of changes, which adds an "Actions" app page - this is basically a "notification replay on steroids" which will also add lots of other options to perform various other actions directly from the watch.

Sadly, at the moment it seems to suffer heavily from the "notifications instantly disappear" problem (they often appear for a fraction of a second, then disappear again) so I'll back on debugging that!

**Comment by benjymous** [comment]
I've just pushed a minor change to your fix, that basically re-pushes the watch back into notify mode immediately after getting the modechanged notification - this seems to fix the problems I was getting with the Actions app - I'll test this for another couple of days and see how it goes.  

My change now only applies to the Digital watch, as I've never experienced an issue with the analog watch (its display buffer update flow is a little different)

**Comment by firetech** [comment]
Ok, I'll try it out. The Actions app seems quite usable, but has been a bit unstable for me (watch restarts or seems to drop the connection). Don't know why and haven't had the time to debug, though... Most probably not MWM's fault, since I'm running experimental firmware. ;)

BTW, I've been running without the timeout in the modeChanged.wait() call all the time now, and haven't had any lockups, so I guess the deadlock I encountered is found and corrected. That said, I think the timeout should be left there, just in case.

**Pull request merged**
