### PR TITLE
Some fixes for the Actions app (and some cleanups along the way)

### PR DESCRIPTION
**Pull request by firetech**
- Added support for "resettable" actions. A long press on the perform button resets the action (what a "reset" means is up to the action). This makes the Clicker action a bit more usable. :) (One idea for the future is to make a "reset" of notification items remove them from the list, in case they are secret or something.)
- Fixed the root cause of the disappearing notifications from the Action app. The problem was that MetaWatchService always called Idle.updateIdle() when an app said it used a button. I refactored the app button handling framework and made buttonPressed return an int instead and added three constants for this: BUTTON_NOT_USED (behaves as false did before), BUTTON_USED (behaves as true) and BUTTON_USED_DONT_UPDATE (behaves as true but suppresses the call to Idle.updateIdle).
- While I was at it, I also moved the MediaPlayerApp button handling from MetaWatchService to MediaPlayerApp's buttonPressed() method, and made the MediaControl methods all take a Context as parameter (instead of an AudioManager in some cases, that is).

I hope I didn't step on any toes doing this. It's just fun to refactor. ;)

### CODE REVIEW

**Comment by benjymous** [comment]
Nope, that's all good - I was planning on moving over the media stuff myself.

Ahh, I should've thought more about that that idle refresh I added - thanks for spotting that :)

**Comment by benjymous** [comment]
Feel free to add any other actions you think might be useful - my next tasks in there are to add a proper framework for registering actions, rather than having them being part of the Actions app, and adding a mechanism for external apps to register actions.  

And a way to configure it all, of course.  The screen will need to scroll, too :)

**Comment by firetech** [comment]
I think had one idea for an action, but I've forgotten it. :P

When I have the time, I'm thinking about making an external Pong game or something. To do that, I'll probably need to add button overrides somehow, since the button codes will be quite random otherwise, and do some work on the external apps framework. :)

**Comment by firetech** [comment]
BTW, are the GeneralPurposePhoneMsg messages for MediaControl (around line 810 in MetaWatchService.java) ever used?

**Comment by benjymous** [comment]
I'm not sure, tbh - they came in as a side-effect alongside another fix 
(by garthy) and I've never really had a chance to investigate

**Comment by firetech** [comment]
Lurking around some old code and github repositories I found the origin of that code snippet. It's used by garthy's old 0.7.x mod, where he built music controls into the watch firmware. I think it's ok to remove support for that, my guess is that noone uses that old mod anymore, and there's no simple way to test the code in MWM without switching firmware.

**Comment by benjymous** [comment]
Cool - yeah, that sounds safe to remove then :)

**Pull request merged**
