### PR TITLE
Actions enhancements.

### PR DESCRIPTION
**Pull request by firetech**
Some fixes from the Braindump, and some code cleanup:
- Move the Action classes from subclasses in the ActionsApp class to a new org.metawatch.manager.actions package. The plan for Actions is for them to be quite central to MWM, and ActionsApp.java was becoming a bit cluttered...
- Move the previously anonymous implementations of the internal Actions to named subclasses in a new InternalActions class (in the org.metawatch.manager.actions package).
- Make the notifications action show the timestamp for the latest notification.
- Show the child count for ContainerActions when selected (by adding " (count)" to the name). I tried, like you suggested in the Braindump, to add the count on its own line above the timestamp (with a line drawn below it) and adding it on the same line as the timestamp, but it looked cluttered and weird...
- Show a title when browsing a ContainerAction. I also tried adding a generic "Actions" title when at the root list, and it looked quite good. Don't know if it's needed, though, as it steals valuable space...
- Hide empty ContainerActions, and make any Action hidable using a new HidableAction interface.

### CODE REVIEW

**Comment by benjymous** [comment]
Awesome :-)

**Comment by firetech** [comment]
I tried to hide empty ContainerActions as well, but it's not trivial at all, and would require a bit of hackish and/or complicated approaches. The problem is moving and drawing the selection.

Just ignoring empty ContainerActions in the drawing loop will cause the selection to be invisible when an empty action is selected, so one would need to move the selection when drawing and check for empty actions when ACTION_NEXT is pressed. Both quite error-prone...

**Comment by firetech** [comment]
Eh. Ignore what I said above. I just remembered that currentActions is overwritten on each update(), so one can (quite) simply remove empty actions from the list. :)

**Comment by firetech** [comment]
There. Empty ContainerActions are now hidden, courtesy of commit ea58bfa, which adds support for hiding any Action that implements HidableAction. :)

**Pull request merged**
