### PR TITLE
Yahoo Weather and some Google Weather fixes

### PR DESCRIPTION
**Pull request by dedee**
- Added GeoLocation feature to Google Weather API code
- Using Apache HttpClient to query the Google API
- GoogleWeather using int instead of float temperature values. There is not enough space on Watch UI to display values behind decimal place (min/max values were truncated)
- Refactored: Moved Google/Wunderground code from Monitor class to separate impl files and created a common interface 
- Made Geo location property default true (would make initial setup easier)
- Refactored: Moved the update check (prevention of requesting weather data too often) to base class AbstractWeatherEngine
- NEW Yahoo Weather API code. It uses the weather API and placefinde API from Yahoo to request location (reverse lookup from coordinates lat/lon to address) and weather data. It requires a so called WOEID, an unique geo place id, which is required to request weather data. Such an ID can either requested for geo location (lat/lon) or an address.

### CODE REVIEW

**Comment by benjymous** [comment]
I'll get this merged in when rm16 is released (not long now!)

**Comment by dedee** [comment]
One note/reminder: The Yahoo weather is currently adding a prefix with time of update to the weather location text (e.g. 10:23 DALLAS). Done this for testing. Should be removed later.

**Comment by benjymous** [comment]
On a related thing, any thoughts on how complex it would be to separate out "Weather Provider" from "Geolocation Provider"?

(I.e. let the user use Wunderground's superior weather data, but still use the google api for the location name)

**Comment by dedee** [comment]
Yes that could be done. We could implement a Google and a Yahoo geolocation provider.

**Comment by dedee** [comment]
I can give it a try. Either before or after merging...

**Comment by dedee** [comment]
I would use the Google Geocoder location by default. If requested by the users we could add a special setting to display Wundergrounds weather station name instead of location if user wants to. But this would make things bit more complicated to the users.

**Comment by benjymous** [comment]
Right, that's all merged over - all three providers seem to be working at a quick test - I'll let you know if I spot any problems.

N.B. I've modified the package name, so it you pull down my changes you'll notice you've got two copies of MWM installed (the old org.metawatch.manager version and the shiny new org.metawatch.communityedition one!)

**Comment by benjymous** [comment]
Let me know how you'd like to be credited in the About box (or edit it yourself)

**Comment by dedee** [comment]
Nice! Would be cool. You can add my realname "Didi Pfeifle" , cause as I understand all the others are also mentioned with their real names.

**Pull request merged**
